model:
  base_learning_rate: 4.5e-06
  target: bev.model.model.DepthAndSegTransformer
  params:
    n_labels: 14
    n_embed: 512
    sfsegnet_config:
      target: bev.model.sfsegnet.sfnet_resnet.DeepR18_SF_deeply_dsn
      params:
        num_classes: 19
        snapshot: ./pretrained/SFSegNet/sfnet_r18_map.pth
    depth_module_config:
      target: bev.model.depth_projection.depth_module.GridAssembler
      params: 
        grid_dim: [50, 50, 10]
        z_range: [1, 51]
        x_range: [-25, 25]
        y_range: [-3, 3]
        num_pix: 480000
    loss_config:
      target: bev.model.loss.DummyLoss

data:
  target: bev.data.data_module.NuscenesDataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 8
    nuscenes_path: /globalwork/data/nuScenes-v1.0
    nuscenes_version: v1.0-trainval
    train:
      target: bev.data.nuscenes_original.NuscenesSegmentationTrain
      params:
        label_path: /home/hoffhues/mono-semantic-maps_labels/nuscenes/map-labels-increased-resolution
        depth_path: /home/hoffhues/NuScenes_images/depth_600*800
        dataset_size: 50000
    validation:
      target: bev.data.nuscenes_original.NuscenesSegmentationValidation
      params:
        label_path: /home/hoffhues/mono-semantic-maps_labels/nuscenes/map-labels-increased-resolution
        depth_path: /home/hoffhues/NuScenes_images/depth_600*800
        preprocess_param:
          crop_region: [150, 0, 650, 500]
          flip_prob: 0.0
          rgb_size: [600, 800]
          bev_size: [50, 50]

