model:
  base_learning_rate: 4.5e-06
  target: bev.model.model.DepthAndSegUpsampler
  params:
    n_labels: 9
    n_embed: 512
    class_names: ['road', 'sidewalk', 'manmade', 'vegetation', 'terrain', 'person',
                  'car', 'truck', 'rider']
    colorize: [[255, 0, 255],
               [75, 0, 75],
               [70, 70, 70],
               [0, 175, 0],
               [150, 240, 80],
               [255, 30, 30],
               [100, 150, 245],
               [80, 30, 180],
               [100, 230, 245],
               [0, 0, 0]]
    ignore_index: 255
    sfsegnet_config:
      target: bev.model.sfsegnet.sfnet_resnet.DeepR18_SF_deeply_dsn
      params:
        num_classes: 19
        snapshot: ./pretrained/SFSegNet/sfnet_r18_map.pth
    depth_module_config:
      target: bev.model.depth_projection.depth_module.GridAssembler
      params:
        grid_dim: [50, 50]
        z_range: [51, 1]
        x_range: [-25, 25]
        num_pix: 344064
    decoder_config:
      target: bev.model.decoder.Decoder
      params:
        in_channels: 512
        num_classes: 9
        final_res: [650, 650]
        predict_vis: True
        layers: [6, 2, 2, 2]
        strides: [1, 2, 2, 2]
    loss_config:
      target: bev.model.loss.CombinedLoss
      params:
        extrinsics:
          translation: [0.0, 0.6, 1.85]
          rotation: [-90, 0, 180]
        background_classes: [2, 3, 4]
        foreground_classes: [0, 1, 5, 6, 7, 8]
        out_shape: [650, 650]
        resolution: 0.077
        priors: nuscenes

data:
  target: bev.data.data_module.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8
    train:
      target: bev.data.nuscenes_bev.NuScenesBEVTrain
      params:
        n_labels: 9
        rgb_root: /globalwork/data/nuScenes-v1.0
        bev_root: /globalwork/hoffhues/PanopticBEV_data/nuScenes_panopticbev
        depth_root: /globalwork/hoffhues/PanopticBEV_images/nuScenes/depth/train
        with_depth: True
        preprocess_param:
          rgb_size: [448, 768]
          bev_size: [650, 650]
          brightness_factor: 0
          contrast_factor: 0
    validation:
      target: bev.data.nuscenes_bev.NuScenesBEVValidation
      params:
        n_labels: 9
        rgb_root: /globalwork/data/nuScenes-v1.0
        bev_root: /globalwork/hoffhues/PanopticBEV_data/nuScenes_panopticbev
        depth_root: /globalwork/hoffhues/PanopticBEV_images/nuScenes/depth/val
        with_depth: True
        preprocess_param:
          rgb_size: [448, 768]
          bev_size: [650, 650]
          flip_prob: 0.
          brightness_factor: 0
          contrast_factor: 0
          
