model:
  base_learning_rate: 4.5e-06
  target: bev.model.baselines.ved.model.VED
  params:
    n_labels: 10
    class_names: ['road', 'sidewalk', 'building', 'wall', 'vegetation', 'terrain', 'person',
                  'rider', 'car', 'truck']
    colorize: [[255, 0, 255],
               [75, 0, 75],
               [255, 200, 0],
               [255, 120, 50],
               [0, 175, 0],
               [150, 240, 80],
               [255, 30, 30],
               [100, 230, 245],
               [100, 150, 245],
               [80, 30, 180],
               [0, 0, 0]]
    ignore_index: 255
    net_config:
      target: bev.model.baselines.ved.nets.ved_model
      params:
        intermediate_size: 4096
        num_class: 10
    loss_config:
      target: bev.model.loss.VEDLoss

data:
  target: bev.data.data_module.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16
    train:
      target: bev.data.kitti360_bev.KITTI360BEVTrain
      params:
        n_labels: 10
        rgb_root: /globalwork/data/KITTI-360
        bev_root: /home/hoffhues/PanopticBEV_data/kitti360_panopticbev
        preprocess_param:
          crop_region: [46, 14, 722, 690]
          flip_prob: 0.5
          rgb_size: [256, 512]
          bev_size: [200, 200]
          brightness_factor: 0
          contrast_factor: 0
          saturation_factor: 0
          hue_factor: 0
    validation:
      target: bev.data.kitti360_bev.KITTI360BEVValidation
      params:
        n_labels: 10
        rgb_root: /globalwork/data/KITTI-360
        bev_root: /home/hoffhues/PanopticBEV_data/kitti360_panopticbev
        preprocess_param:
          crop_region: [46, 14, 722, 690]
          flip_prob: 0.
          rgb_size: [256, 512]
          bev_size: [200, 200]
          brightness_factor: 0
          contrast_factor: 0
          saturation_factor: 0
          hue_factor: 0
